window.esdocSearchIndex = [
  [
    "@aureooms/js-number/src/constants/$0.js~$0",
    "function/index.html#static-function-$0",
    "<span>$0</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/constants/$0.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/constants/$1.js~$1",
    "function/index.html#static-function-$1",
    "<span>$1</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/constants/$1.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/constants/$2.js~$2",
    "function/index.html#static-function-$2",
    "<span>$2</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/constants/$2.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/constants/$5.js~$5",
    "function/index.html#static-function-$5",
    "<span>$5</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/constants/$5.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/constants/$_1.js~$_1",
    "function/index.html#static-function-$_1",
    "<span>$_1</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/constants/$_1.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/trigonometry/pi.js~pi",
    "variable/index.html#static-variable-PI",
    "<span>PI</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/trigonometry/PI.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-number/src/arithmetic/constants/add1.js~add1",
    "function/index.html#static-function-add1",
    "<span>add1</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/constants/add1.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/add.js~add",
    "function/index.html#static-function-add",
    "<span>add</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/add.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/trigonometry/atan2.js~atan2",
    "variable/index.html#static-variable-atan2",
    "<span>atan2</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/trigonometry/atan2.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-number/src/memory/copy.js~copy",
    "function/index.html#static-function-copy",
    "<span>copy</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/memory/copy.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/trigonometry/cos.js~cos",
    "variable/index.html#static-variable-cos",
    "<span>cos</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/trigonometry/cos.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-number/src/compare/decreasing.js~decreasing",
    "function/index.html#static-function-decreasing",
    "<span>decreasing</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/compare/decreasing.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/constants/div2.js~div2",
    "function/index.html#static-function-div2",
    "<span>div2</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/constants/div2.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/special/div2n.js~div2n",
    "function/index.html#static-function-div2n",
    "<span>div2n</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/special/div2n.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/div.js~div",
    "function/index.html#static-function-div",
    "<span>div</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/div.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/divmod.js~divmod",
    "function/index.html#static-function-divmod",
    "<span>divmod</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/divmod.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/predicate/constants/eq0.js~eq0",
    "function/index.html#static-function-eq0",
    "<span>eq0</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/predicate/constants/eq0.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/predicate/constants/eq1.js~eq1",
    "function/index.html#static-function-eq1",
    "<span>eq1</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/predicate/constants/eq1.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/predicate/eq.js~eq",
    "function/index.html#static-function-eq",
    "<span>eq</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/predicate/eq.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/predicate/constants/eq_1.js~eq_1",
    "function/index.html#static-function-eq_1",
    "<span>eq_1</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/predicate/constants/eq_1.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/exponential/exp.js~exp",
    "variable/index.html#static-variable-exp",
    "<span>exp</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/exponential/exp.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-number/src/predicate/constants/ge1.js~ge1",
    "function/index.html#static-function-ge1",
    "<span>ge1</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/predicate/constants/ge1.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/predicate/ge.js~ge",
    "function/index.html#static-function-ge",
    "<span>ge</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/predicate/ge.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/predicate/constants/gt0.js~gt0",
    "function/index.html#static-function-gt0",
    "<span>gt0</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/predicate/constants/gt0.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/predicate/constants/gt1.js~gt1",
    "function/index.html#static-function-gt1",
    "<span>gt1</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/predicate/constants/gt1.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/predicate/gt.js~gt",
    "function/index.html#static-function-gt",
    "<span>gt</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/predicate/gt.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/constants/iadd1.js~iadd1",
    "function/index.html#static-function-iadd1",
    "<span>iadd1</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/constants/iadd1.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/iadd.js~iadd",
    "function/index.html#static-function-iadd",
    "<span>iadd</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/iadd.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/constants/idiv2.js~idiv2",
    "function/index.html#static-function-idiv2",
    "<span>idiv2</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/constants/idiv2.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/idiv.js~idiv",
    "function/index.html#static-function-idiv",
    "<span>idiv</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/idiv.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/idivmod.js~idivmod",
    "function/index.html#static-function-idivmod",
    "<span>idivmod</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/idivmod.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/imod.js~imod",
    "function/index.html#static-function-imod",
    "<span>imod</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/imod.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/constants/imul2.js~imul2",
    "function/index.html#static-function-imul2",
    "<span>imul2</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/constants/imul2.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/constants/imul5.js~imul5",
    "function/index.html#static-function-imul5",
    "<span>imul5</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/constants/imul5.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/imul.js~imul",
    "function/index.html#static-function-imul",
    "<span>imul</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/imul.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/compare/increasing.js~increasing",
    "function/index.html#static-function-increasing",
    "<span>increasing</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/compare/increasing.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/exponential/constants/ipow2.js~ipow2",
    "function/index.html#static-function-ipow2",
    "<span>ipow2</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/exponential/constants/ipow2.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/ishl.js~ishl",
    "function/index.html#static-function-ishl",
    "<span>ishl</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/ishl.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/ishr.js~ishr",
    "function/index.html#static-function-ishr",
    "<span>ishr</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/ishr.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/ishu.js~ishu",
    "function/index.html#static-function-ishu",
    "<span>ishu</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/ishu.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/constants/isub1.js~isub1",
    "function/index.html#static-function-isub1",
    "<span>isub1</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/constants/isub1.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/isub.js~isub",
    "function/index.html#static-function-isub",
    "<span>isub</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/isub.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/predicate/constants/le1.js~le1",
    "function/index.html#static-function-le1",
    "<span>le1</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/predicate/constants/le1.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/predicate/le.js~le",
    "function/index.html#static-function-le",
    "<span>le</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/predicate/le.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/logarithmic/log2.js~log2",
    "function/index.html#static-function-log2",
    "<span>log2</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/logarithmic/log2.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/logarithmic/log.js~log",
    "function/index.html#static-function-log",
    "<span>log</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/logarithmic/log.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/logarithmic/loge.js~loge",
    "function/index.html#static-function-loge",
    "<span>loge</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/logarithmic/loge.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/logarithmic/loglog2.js~loglog2",
    "function/index.html#static-function-loglog2",
    "<span>loglog2</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/logarithmic/loglog2.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/logarithmic/loglog.js~loglog",
    "function/index.html#static-function-loglog",
    "<span>loglog</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/logarithmic/loglog.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/logarithmic/logloge.js~logloge",
    "function/index.html#static-function-logloge",
    "<span>logloge</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/logarithmic/logloge.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/predicate/constants/lt1.js~lt1",
    "function/index.html#static-function-lt1",
    "<span>lt1</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/predicate/constants/lt1.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/predicate/lt.js~lt",
    "function/index.html#static-function-lt",
    "<span>lt</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/predicate/lt.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/mod.js~mod",
    "function/index.html#static-function-mod",
    "<span>mod</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/mod.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/constants/mul2.js~mul2",
    "function/index.html#static-function-mul2",
    "<span>mul2</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/constants/mul2.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/constants/mul5.js~mul5",
    "function/index.html#static-function-mul5",
    "<span>mul5</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/constants/mul5.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/mul.js~mul",
    "function/index.html#static-function-mul",
    "<span>mul</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/mul.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/predicate/ne.js~ne",
    "function/index.html#static-function-ne",
    "<span>ne</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/predicate/ne.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/neg.js~neg",
    "function/index.html#static-function-neg",
    "<span>neg</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/neg.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/io/parse.js~parse",
    "function/index.html#static-function-parse",
    "<span>parse</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/io/parse.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/exponential/constants/pow2.js~pow2",
    "function/index.html#static-function-pow2",
    "<span>pow2</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/exponential/constants/pow2.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/exponential/pow.js~pow",
    "variable/index.html#static-variable-pow",
    "<span>pow</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/exponential/pow.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-number/src/arithmetic/shl.js~shl",
    "function/index.html#static-function-shl",
    "<span>shl</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/shl.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/shr.js~shr",
    "function/index.html#static-function-shr",
    "<span>shr</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/shr.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/shu.js~shu",
    "function/index.html#static-function-shu",
    "<span>shu</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/shu.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/trigonometry/sin.js~sin",
    "variable/index.html#static-variable-sin",
    "<span>sin</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/trigonometry/sin.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-number/src/exponential/sqrt.js~sqrt",
    "variable/index.html#static-variable-sqrt",
    "<span>sqrt</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/exponential/sqrt.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-number/src/io/stringify.js~stringify",
    "function/index.html#static-function-stringify",
    "<span>stringify</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/io/stringify.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/constants/sub1.js~sub1",
    "function/index.html#static-function-sub1",
    "<span>sub1</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/constants/sub1.js</span>",
    "function"
  ],
  [
    "@aureooms/js-number/src/arithmetic/sub.js~sub",
    "function/index.html#static-function-sub",
    "<span>sub</span> <span class=\"search-result-import-path\">@aureooms/js-number/src/arithmetic/sub.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/arithmetic/add.js",
    "file/src/arithmetic/add.js.html",
    "src/arithmetic/add.js",
    "file"
  ],
  [
    "src/arithmetic/constants/add1.js",
    "file/src/arithmetic/constants/add1.js.html",
    "src/arithmetic/constants/add1.js",
    "file"
  ],
  [
    "src/arithmetic/constants/div2.js",
    "file/src/arithmetic/constants/div2.js.html",
    "src/arithmetic/constants/div2.js",
    "file"
  ],
  [
    "src/arithmetic/constants/iadd1.js",
    "file/src/arithmetic/constants/iadd1.js.html",
    "src/arithmetic/constants/iadd1.js",
    "file"
  ],
  [
    "src/arithmetic/constants/idiv2.js",
    "file/src/arithmetic/constants/idiv2.js.html",
    "src/arithmetic/constants/idiv2.js",
    "file"
  ],
  [
    "src/arithmetic/constants/imul2.js",
    "file/src/arithmetic/constants/imul2.js.html",
    "src/arithmetic/constants/imul2.js",
    "file"
  ],
  [
    "src/arithmetic/constants/imul5.js",
    "file/src/arithmetic/constants/imul5.js.html",
    "src/arithmetic/constants/imul5.js",
    "file"
  ],
  [
    "src/arithmetic/constants/isub1.js",
    "file/src/arithmetic/constants/isub1.js.html",
    "src/arithmetic/constants/isub1.js",
    "file"
  ],
  [
    "src/arithmetic/constants/mul2.js",
    "file/src/arithmetic/constants/mul2.js.html",
    "src/arithmetic/constants/mul2.js",
    "file"
  ],
  [
    "src/arithmetic/constants/mul5.js",
    "file/src/arithmetic/constants/mul5.js.html",
    "src/arithmetic/constants/mul5.js",
    "file"
  ],
  [
    "src/arithmetic/constants/sub1.js",
    "file/src/arithmetic/constants/sub1.js.html",
    "src/arithmetic/constants/sub1.js",
    "file"
  ],
  [
    "src/arithmetic/div.js",
    "file/src/arithmetic/div.js.html",
    "src/arithmetic/div.js",
    "file"
  ],
  [
    "src/arithmetic/divmod.js",
    "file/src/arithmetic/divmod.js.html",
    "src/arithmetic/divmod.js",
    "file"
  ],
  [
    "src/arithmetic/iadd.js",
    "file/src/arithmetic/iadd.js.html",
    "src/arithmetic/iadd.js",
    "file"
  ],
  [
    "src/arithmetic/idiv.js",
    "file/src/arithmetic/idiv.js.html",
    "src/arithmetic/idiv.js",
    "file"
  ],
  [
    "src/arithmetic/idivmod.js",
    "file/src/arithmetic/idivmod.js.html",
    "src/arithmetic/idivmod.js",
    "file"
  ],
  [
    "src/arithmetic/imod.js",
    "file/src/arithmetic/imod.js.html",
    "src/arithmetic/imod.js",
    "file"
  ],
  [
    "src/arithmetic/imul.js",
    "file/src/arithmetic/imul.js.html",
    "src/arithmetic/imul.js",
    "file"
  ],
  [
    "src/arithmetic/ishl.js",
    "file/src/arithmetic/ishl.js.html",
    "src/arithmetic/ishl.js",
    "file"
  ],
  [
    "src/arithmetic/ishr.js",
    "file/src/arithmetic/ishr.js.html",
    "src/arithmetic/ishr.js",
    "file"
  ],
  [
    "src/arithmetic/ishu.js",
    "file/src/arithmetic/ishu.js.html",
    "src/arithmetic/ishu.js",
    "file"
  ],
  [
    "src/arithmetic/isub.js",
    "file/src/arithmetic/isub.js.html",
    "src/arithmetic/isub.js",
    "file"
  ],
  [
    "src/arithmetic/mod.js",
    "file/src/arithmetic/mod.js.html",
    "src/arithmetic/mod.js",
    "file"
  ],
  [
    "src/arithmetic/mul.js",
    "file/src/arithmetic/mul.js.html",
    "src/arithmetic/mul.js",
    "file"
  ],
  [
    "src/arithmetic/neg.js",
    "file/src/arithmetic/neg.js.html",
    "src/arithmetic/neg.js",
    "file"
  ],
  [
    "src/arithmetic/shl.js",
    "file/src/arithmetic/shl.js.html",
    "src/arithmetic/shl.js",
    "file"
  ],
  [
    "src/arithmetic/shr.js",
    "file/src/arithmetic/shr.js.html",
    "src/arithmetic/shr.js",
    "file"
  ],
  [
    "src/arithmetic/shu.js",
    "file/src/arithmetic/shu.js.html",
    "src/arithmetic/shu.js",
    "file"
  ],
  [
    "src/arithmetic/special/div2n.js",
    "file/src/arithmetic/special/div2n.js.html",
    "src/arithmetic/special/div2n.js",
    "file"
  ],
  [
    "src/arithmetic/sub.js",
    "file/src/arithmetic/sub.js.html",
    "src/arithmetic/sub.js",
    "file"
  ],
  [
    "src/compare/decreasing.js",
    "file/src/compare/decreasing.js.html",
    "src/compare/decreasing.js",
    "file"
  ],
  [
    "src/compare/increasing.js",
    "file/src/compare/increasing.js.html",
    "src/compare/increasing.js",
    "file"
  ],
  [
    "src/constants/$0.js",
    "file/src/constants/$0.js.html",
    "src/constants/$0.js",
    "file"
  ],
  [
    "src/constants/$1.js",
    "file/src/constants/$1.js.html",
    "src/constants/$1.js",
    "file"
  ],
  [
    "src/constants/$2.js",
    "file/src/constants/$2.js.html",
    "src/constants/$2.js",
    "file"
  ],
  [
    "src/constants/$5.js",
    "file/src/constants/$5.js.html",
    "src/constants/$5.js",
    "file"
  ],
  [
    "src/constants/$_1.js",
    "file/src/constants/$_1.js.html",
    "src/constants/$_1.js",
    "file"
  ],
  [
    "src/exponential/constants/ipow2.js",
    "file/src/exponential/constants/ipow2.js.html",
    "src/exponential/constants/ipow2.js",
    "file"
  ],
  [
    "src/exponential/constants/pow2.js",
    "file/src/exponential/constants/pow2.js.html",
    "src/exponential/constants/pow2.js",
    "file"
  ],
  [
    "src/exponential/exp.js",
    "file/src/exponential/exp.js.html",
    "src/exponential/exp.js",
    "file"
  ],
  [
    "src/exponential/pow.js",
    "file/src/exponential/pow.js.html",
    "src/exponential/pow.js",
    "file"
  ],
  [
    "src/exponential/sqrt.js",
    "file/src/exponential/sqrt.js.html",
    "src/exponential/sqrt.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/io/parse.js",
    "file/src/io/parse.js.html",
    "src/io/parse.js",
    "file"
  ],
  [
    "src/io/stringify.js",
    "file/src/io/stringify.js.html",
    "src/io/stringify.js",
    "file"
  ],
  [
    "src/logarithmic/log.js",
    "file/src/logarithmic/log.js.html",
    "src/logarithmic/log.js",
    "file"
  ],
  [
    "src/logarithmic/log2.js",
    "file/src/logarithmic/log2.js.html",
    "src/logarithmic/log2.js",
    "file"
  ],
  [
    "src/logarithmic/loge.js",
    "file/src/logarithmic/loge.js.html",
    "src/logarithmic/loge.js",
    "file"
  ],
  [
    "src/logarithmic/loglog.js",
    "file/src/logarithmic/loglog.js.html",
    "src/logarithmic/loglog.js",
    "file"
  ],
  [
    "src/logarithmic/loglog2.js",
    "file/src/logarithmic/loglog2.js.html",
    "src/logarithmic/loglog2.js",
    "file"
  ],
  [
    "src/logarithmic/logloge.js",
    "file/src/logarithmic/logloge.js.html",
    "src/logarithmic/logloge.js",
    "file"
  ],
  [
    "src/memory/copy.js",
    "file/src/memory/copy.js.html",
    "src/memory/copy.js",
    "file"
  ],
  [
    "src/predicate/constants/eq0.js",
    "file/src/predicate/constants/eq0.js.html",
    "src/predicate/constants/eq0.js",
    "file"
  ],
  [
    "src/predicate/constants/eq1.js",
    "file/src/predicate/constants/eq1.js.html",
    "src/predicate/constants/eq1.js",
    "file"
  ],
  [
    "src/predicate/constants/eq_1.js",
    "file/src/predicate/constants/eq_1.js.html",
    "src/predicate/constants/eq_1.js",
    "file"
  ],
  [
    "src/predicate/constants/ge1.js",
    "file/src/predicate/constants/ge1.js.html",
    "src/predicate/constants/ge1.js",
    "file"
  ],
  [
    "src/predicate/constants/gt0.js",
    "file/src/predicate/constants/gt0.js.html",
    "src/predicate/constants/gt0.js",
    "file"
  ],
  [
    "src/predicate/constants/gt1.js",
    "file/src/predicate/constants/gt1.js.html",
    "src/predicate/constants/gt1.js",
    "file"
  ],
  [
    "src/predicate/constants/le1.js",
    "file/src/predicate/constants/le1.js.html",
    "src/predicate/constants/le1.js",
    "file"
  ],
  [
    "src/predicate/constants/lt1.js",
    "file/src/predicate/constants/lt1.js.html",
    "src/predicate/constants/lt1.js",
    "file"
  ],
  [
    "src/predicate/eq.js",
    "file/src/predicate/eq.js.html",
    "src/predicate/eq.js",
    "file"
  ],
  [
    "src/predicate/ge.js",
    "file/src/predicate/ge.js.html",
    "src/predicate/ge.js",
    "file"
  ],
  [
    "src/predicate/gt.js",
    "file/src/predicate/gt.js.html",
    "src/predicate/gt.js",
    "file"
  ],
  [
    "src/predicate/le.js",
    "file/src/predicate/le.js.html",
    "src/predicate/le.js",
    "file"
  ],
  [
    "src/predicate/lt.js",
    "file/src/predicate/lt.js.html",
    "src/predicate/lt.js",
    "file"
  ],
  [
    "src/predicate/ne.js",
    "file/src/predicate/ne.js.html",
    "src/predicate/ne.js",
    "file"
  ],
  [
    "src/trigonometry/pi.js",
    "file/src/trigonometry/PI.js.html",
    "src/trigonometry/PI.js",
    "file"
  ],
  [
    "src/trigonometry/atan2.js",
    "file/src/trigonometry/atan2.js.html",
    "src/trigonometry/atan2.js",
    "file"
  ],
  [
    "src/trigonometry/cos.js",
    "file/src/trigonometry/cos.js.html",
    "src/trigonometry/cos.js",
    "file"
  ],
  [
    "src/trigonometry/sin.js",
    "file/src/trigonometry/sin.js.html",
    "src/trigonometry/sin.js",
    "file"
  ]
]